<?php
require_once __DIR__ . '/config/database.php';

try {
    $db = new Database();
    $conn = $db->getConnection();

    // Read final_migration.sql
    $sqlFile = __DIR__ . '/../final_migration.sql';
    if (!file_exists($sqlFile)) {
        die("Error: Migration file not found at $sqlFile\n");
    }

    $sql = file_get_contents($sqlFile);

    echo "Running migration...\n";

    // Split standard SQL dumps by semicolon is tricky but for simple dumps generated by our script it might work.
    // However, our script generates bulk inserts.
    // Let's try to run it as a single exec() call if the driver supports multi statements.
    // PDO default for MySQL is usually single statement unless emulate prepares is on.

    // Check if we need to split manually. A naive split by ";\n" is safer than just ";"
    // Our generator puts ";\n" at the end of statements.

    $statements = explode(";\n", $sql);

    foreach ($statements as $statement) {
        $stmtStr = trim($statement);
        if (empty($stmtStr) || strpos($stmtStr, '--') === 0)
            continue;

        try {
            $conn->exec($stmtStr);
        } catch (PDOException $e) {
            // Check if error is minor (e.g. duplicate entry for primary key if re-running)
            echo "Warning/Error on statement: " . substr($stmtStr, 0, 50) . "...\n";
            echo "Message: " . $e->getMessage() . "\n";
            // continue; // Continue on error? Maybe not for structure.
        }
    }

    echo "Migration completed successfully!\n";

} catch (Exception $e) {
    echo "Fatal Error: " . $e->getMessage() . "\n";
}
?>