<?php
require_once __DIR__ . '/config/database.php';

try {
    $db = new Database();
    $conn = $db->getConnection();

    // Read final_migration.sql
    $sqlFile = __DIR__ . '/migration_final.sql';
    if (!file_exists($sqlFile)) {
        die("Error: Migration file not found at $sqlFile\n");
    }

    $sql = file_get_contents($sqlFile);

    echo "Running migration...\n";

    // Explicitly disable FK checks for this connection session
    $conn->exec("SET FOREIGN_KEY_CHECKS=0");

    // Split standard SQL dumps by semicolon is tricky but for simple dumps generated by our script it might work.
    $statements = explode(";\n", $sql);

    foreach ($statements as $statement) {
        $stmtStr = trim($statement);
        if (empty($stmtStr) || strpos($stmtStr, '--') === 0)
            continue;

        try {
            $conn->exec($stmtStr);
        } catch (PDOException $e) {
            // Check if error is minor (e.g. duplicate entry for primary key if re-running)
            echo "Warning/Error on statement: " . substr($stmtStr, 0, 50) . "...\n";
            echo "Message: " . $e->getMessage() . "\n";
            // continue; // Continue on error? Maybe not for structure.
        }
    }

    echo "Migration completed successfully!\n";

} catch (Exception $e) {
    echo "Fatal Error: " . $e->getMessage() . "\n";
}
?>