const fs = require('fs');
const path = require('path');

const inputFile = path.join(__dirname, '../ouycwnsb_db.sql');
const outputFile = path.join(__dirname, '../final_migration.sql');

const sqlContent = fs.readFileSync(inputFile, 'utf8');

// Helper to extract values from INSERT statement
function extractValues(insertStatement) {
    // Basic regex to find values inside parens after VALUES
    // This is fragile but works for standard dumps without complex nested parens in strings
    const match = insertStatement.match(/VALUES\s*((?:\(.*\)[,;]?\s*)+)/i);
    if (!match) return [];

    // Split by ),( to handle multiple rows, but be careful with strings
    // A better approach is to not parse strict SQL but just grab the lines and regex replace
    // However, for user_mapel aggregation we need to PARSE.

    // Let's use a simpler line-by-line approach for aggregation
}

// Data structures for aggregation
const userMapel = {}; // userId -> [mapel]
const userKelas = {}; // userId -> [kelas]

const lines = sqlContent.split('\n');
const insertStatements = [];

// First pass: Collect pivot data
lines.forEach(line => {
    if (line.startsWith("INSERT INTO `user_mapel`")) {
        // Parse: ('uid', 'mapel'), ...
        const valuesPart = line.substring(line.indexOf('VALUES') + 6).trim();
        // Remove trailing ;
        const cleanValues = valuesPart.replace(/;$/, '');
        // Split by ),(
        const rows = cleanValues.split(/\),\s*\(/);
        rows.forEach(row => {
            // Clean parens
            const cleanRow = row.replace(/^\(/, '').replace(/\)$/, '');
            // Split by comma
            const cols = cleanRow.split(/,\s*(?=(?:[^']*'[^']*')*[^']*$)/); // Split by comma outside quotes
            const userId = cols[0].replace(/'/g, '').trim();
            const mapel = cols[1].replace(/'/g, '').trim();

            if (!userMapel[userId]) userMapel[userId] = [];
            if (!userMapel[userId].includes(mapel)) userMapel[userId].push(mapel);
        });
    }

    if (line.startsWith("INSERT INTO `user_kelas`")) {
        const valuesPart = line.substring(line.indexOf('VALUES') + 6).trim();
        const cleanValues = valuesPart.replace(/;$/, '');
        const rows = cleanValues.split(/\),\s*\(/);
        rows.forEach(row => {
            const cleanRow = row.replace(/^\(/, '').replace(/\)$/, '');
            const cols = cleanRow.split(/,\s*(?=(?:[^']*'[^']*')*[^']*$)/);
            const userId = cols[0].replace(/'/g, '').trim();
            const kelas = cols[1].replace(/'/g, '').trim();

            if (!userKelas[userId]) userKelas[userId] = [];
            if (!userKelas[userId].includes(kelas)) userKelas[userId].push(kelas);
        });
    }
});

let outputSQL = "-- Migration Script generated by Antigravity\n\n";

// Table specific transformations
lines.forEach(line => {
    if (line.startsWith("INSERT INTO `users`")) {
        // Transform to `profiles`
        // users cols: id, nama, email, password_hash, asal_sekolah, pendidikan_terakhir, jurusan, status_kepegawaian, role, is_active, created_at, updated_at, ukuran_baju, no_hp, foto_profile, subscription_status
        // profiles cols: id, nama, asal_sekolah, pendidikan_terakhir, jurusan, status_kepegawaian, role, is_active, ukuran_baju, no_hp, foto_profile, mapel, kelas, created_at, updated_at, email, password_hash

        // We need to inject mapel and kelas into the values

        const valuesPart = line.substring(line.indexOf('VALUES') + 6).trim().replace(/;$/, '');
        const rows = valuesPart.split(/\),\s*\(/);

        const newRows = rows.map(row => {
            const cleanRow = row.replace(/^\(/, '').replace(/\)$/, '');
            const cols = cleanRow.split(/,\s*(?=(?:[^']*'[^']*')*[^']*$)/);

            // Map columns by index (based on known structure from dump)
            // 0: id, 1: nama, 2: email, 3: password_hash, 4: asal_sekolah, 5: pendidikan, 6: jurusan, 7: status, 8: role, 9: is_active, 10: created_at, 11: updated_at, 12: ukuran_baju, 13: no_hp, 14: foto_profile, 15: sub_status

            const userId = cols[0].replace(/'/g, '').trim();
            const mapelArray = userMapel[userId] ? `'{"${userMapel[userId].join('","')}"}'` : "NULL"; // Postgres array format? MySQL doesn't support array types directly usually, stores as JSON or Text. Postgres supports ARRAY literal '{a,b}'. MySQL standard `profiles` schema has `mapel TEXT[]` which in MySQL context usually means JSON or comma separated string.
            // But wait, `20260210_mysql_updates.sql` didn't change `mapel TEXT[]`.
            // If the target is MySQL, `TEXT[]` is not valid. It probably became `TEXT` or `JSON`.
            // Assuming JSON array for MySQL: `["a", "b"]`

            const mapelJSON = userMapel[userId] ? `'${JSON.stringify(userMapel[userId])}'` : "NULL";
            const kelasJSON = userKelas[userId] ? `'${JSON.stringify(userKelas[userId])}'` : "NULL";

            // Construct new row for profiles
            // INSERT INTO profiles (id, nama, email, password_hash, role, is_active, asal_sekolah, pendidikan_terakhir, jurusan, status_kepegawaian, ukuran_baju, no_hp, foto_profile, mapel, kelas, created_at, updated_at)

            return `(${cols[0]}, ${cols[1]}, ${cols[2]}, ${cols[3]}, ${cols[8]}, ${cols[9]}, ${cols[4]}, ${cols[5]}, ${cols[6]}, ${cols[7]}, ${cols[12]}, ${cols[13]}, ${cols[14]}, ${mapelJSON}, ${kelasJSON}, ${cols[10]}, ${cols[11]})`;
        });

        outputSQL += `INSERT INTO \`profiles\` (id, nama, email, password_hash, role, is_active, asal_sekolah, pendidikan_terakhir, jurusan, status_kepegawaian, ukuran_baju, no_hp, foto_profile, mapel, kelas, created_at, updated_at) VALUES\n${newRows.join(',\n')};\n\n`;
    }
    else if (line.startsWith("INSERT INTO `events`")) {
        // Just copy, maybe fix certificateUrl
        let newLine = line.replace("`certificateUrl`", "`certificate_url`");
        outputSQL += newLine + "\n";
    }
    else if (line.startsWith("INSERT INTO `event_participants`")) {
        outputSQL += line + "\n";
    }
    else if (line.startsWith("INSERT INTO `subscriptions`")) {
        // Map to premium_subscriptions?
        // Check columns
        outputSQL += line.replace("INSERT INTO `subscriptions`", "INSERT INTO `premium_subscriptions`") + "\n";
    }
    else if (line.startsWith("INSERT INTO `site_content`")) {
        outputSQL += line + "\n";
    }
});

fs.writeFileSync(outputFile, outputSQL);
console.log('Migration script generated:', outputFile);
